### ISSUE TITLE
Suggestion to use Cobra

### ISSUE THREAD

**Issue by mmstick** [aisola/go-coreutils#36]
Check out this webpage detailing Cobra, and how it would apply to this project.
http://blog.gopheracademy.com/advent-2014/introducing-cobra/

**Comment by tehbilly** [comment]
Either of those utilities would be a boon to this project. My real concern with the success of a project like this would be the size. Go is beautiful, wonderful, makes bacon, and we all love it. However the binary size for tiny utilities is a bit terrible. But that's fine!

I think a great project that handles this particular domain well already is busybox. It has a handy feature that lets you use the same executable to run all of the utilities. What this means is that you can symlink all of your commands to the single executable, and it just works as all of them work. There's no reason you couldn't implement that here, with or without using a third party library to manage the commands themselves.

A completely nonsensical (but working) example I threw together quickly can be found [in this gist](https://gist.github.com/tehbilly/043f615d09baf7e5f7a7). Compile this, create symlinks to it, using the different symlinks gets you different operations. Just an overall suggestion.

When I have time I may be able to throw together a PR with a properly thought out command interface, if you'd like.
