### ISSUE TITLE
mkdir parent/verbose output not identical to Gnu mkdir

### ISSUE THREAD

**Issue by Don42** [aisola/go-coreutils#39]
As described in 0c2954475526f3ae0186cc99c123c0e372c0f58b the output of this mkdir implementation shows only the path to the deepest folder, whereas gnu mkdir list all intermediary folders that were created.
This happens when --verbose and --parents options are combined.
Is it necessary for this implementation to provide the same output as the gnu version?

**Comment by aisola** [comment]
Ideally, this project should nearly mirror the functionality of GNU coreutils.

**Comment by Don42** [comment]
Since this behavior is actually in the manpage, I am going to implement it.
